apiVersion: v1
kind: PersistentVolume
metadata:
  name: flink-historyserver-efs-pv
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: efs-flink-history
  csi:
    driver: efs.csi.aws.com
    volumeHandle: "fs-0af85c779d45377d8"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: flink-historyserver-efs-pvc
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: efs-flink-history
  resources:
    requests:
      storage: 5Gi